package parser

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/EdgarOrtegaRamirez/configforge/pkg/config"
)

// ParseDotenv parses a .env file into a config Tree.
func ParseDotenv(path string) (*config.Tree, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return ParseDotenvBytes(data)
}

// ParseDotenvBytes parses .env bytes into a config Tree.
func ParseDotenvBytes(data []byte) (*config.Tree, error) {
	tree := config.NewTree()
	tree.Format = "dotenv"

	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || line[0] == '#' {
			continue
		}

		// KEY=VALUE
		if idx := strings.Index(line, "="); idx > 0 {
			key := strings.TrimSpace(line[:idx])
			value := strings.TrimSpace(line[idx+1:])

			// Strip quotes
			if len(value) >= 2 {
				if (value[0] == '"' && value[len(value)-1] == '"') ||
					(value[0] == '\'' && value[len(value)-1] == '\'') {
					value = value[1 : len(value)-1]
				}
			}

			tree.Root.SetKey(key, config.NewScalarValue(value))
		}
	}

	return tree, scanner.Err()
}

// WriteDotenv writes a config Tree as .env.
func WriteDotenv(tree *config.Tree, path string) error {
	data, err := MarshalDotenv(tree)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

// MarshalDotenv marshals a config Tree to .env bytes.
func MarshalDotenv(tree *config.Tree) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString("# Generated by ConfigForge\n")

	for _, child := range tree.Root.Children {
		if child.Value.Kind == config.KindScalar {
			val := fmt.Sprintf("%v", child.Value.Scalar)
			// Quote values containing spaces
			if strings.Contains(val, " ") {
				val = fmt.Sprintf("%q", val)
			}
			sb.WriteString(fmt.Sprintf("%s=%s\n", child.Key, val))
		}
	}

	return []byte(sb.String()), nil
}
